# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4688fee15f452c2b8d610a199172e1af"
name = "bowerbird-archive-digitisation"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,write_customers,write_draft_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth", "http://localhost:3457/auth/callback" ]
