api_version = "2026-01"

[[extensions]]
uid = "32cad21c-a827-3644-1247-6442d3c6ae6603b626d6"
type = "ui_extension"
name = "Donation"
handle = "checkout-donation-upsell"

  [[extensions.targeting]]
  target = "purchase.checkout.actions.render-before"
  module = "./src/Checkout.jsx"

  [extensions.capabilities]
  api_access = true
